commentcrud/urls.py
from django.urls import path
from .import views

urlpatterns=[
    path('commentcreate/<int:post_id>', views.commentcreate, name='commentcreate'),
    path('/edit', views.edit, name="edit"),
    path('/postupdate/<int:comment_id>', views.postupdate, name='postupdate'),
    path('/postdelete/<int:comment_id>', views.postdelete, name='postdelete'),
]

postcrud/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list/', views.list, name='list'),
    path('postnew/', views.postnew, name='postnew'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('postshow/<int:post_id>', views.postshow, name='postshow'),
]

vacation_1stproject/urls.py
from django.contrib import admin
from django.urls import path, include
import postcrud.views
import commentcrud.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', postcrud.views.list),
    path('postcrud/', include('postcrud.urls')),
    path('commentcrud/', include('commentcrud.urls')),
]

commentcrud/models.py
from django.db import models
from postcrud.models import Post

# Create your models here.
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

postcrud/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

commentcrud/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

postcrud/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

commentcrud/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CommentForm
from postcrud.models import Post
from .models import Comment

# Create your views here.

def commentcreate(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('postshow', post_id=post.pk)
        else:
            redirect('list')
    else:
        form = CommentForm()
        return render(request, 'postshow.html', {'form':form, 'post':post})

def edit(request):
    return render(request, 'edit.html')

def postupdate(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('postshow', coment_id=comment.pk)
    else:
        form = CommentForm(instance=comment)
        return render(request, 'edit.html', {'form':form})

def postdelete(request, comment_id):
    post = get_object_or_404(Comment, pk=comment_id)
    post.delete()
    return redirect('list')

postcrud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm
from .models import Post

# Create your views here.
def list(request):
    posts = Post.objects.all()
    return render(request, 'list.html', {'posts': posts})

def postshow(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'postshow.html', {'post': post})

def postnew(request):
    return render(request, 'postnew.html')

def postcreate(request):
    if request.method=='POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('list')
        else:
            return redirect('list')
    else:
        form = PostForm()
        return render(request, 'postnew.html', {'form': form})

commentcrud/templates/edit.html
<h1>수정</h1>
<form method="POST">
    {% csrf_token %}
        {{ form.as_p }}
    <br>
    <input type="submit" value="수정하기" name="edit">
</form>

postcrud/templates/list.html
<h1>글 목록</h1>
<a href="{% url 'postcreate' %}">새 글 작성</a>

{% for post in posts %}
    <h3><a href="{% url 'postshow' post.id %}">{{post.title}}</a></h3>
{% endfor %}

postcrud/templates/postnew.html
<h1>글 작성하기</h1>
<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'>글 작성</button>
</form>

postcrud/templates/postshow.html
<h4><a href="{% url 'list' %}">뒤로가기</a></h4>
<h4>제목 : {{ post.title }}</h4>
<h4>내용 : {{ post.content }}</h4>
<br>
<a href="{% url 'commentcreate' post.id %}">댓글 작성하기</a>
<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'>댓글 등록</button>
</form>

<br>
<h4>댓글 목록</h4>
{% for comment in post.comment_set.all %}
    {{ comment.content }}
    <a href="{% url 'postupdate' comment.id %}">수정</a> &nbsp;
    <a href="{% url 'postdelete' comment.id %}" onclick="return confirm('정말 삭제?')">삭제</a><br>
{% endfor %}